//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int id { get; set; }
        public int customerId { get; set; }
        public int shopId { get; set; }
        public string message { get; set; }
        public System.DateTime feedbackDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Shops Shops { get; set; }
    }
}
