//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string imagePath { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
