//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSeats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomSeats()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int roomId { get; set; }
        public int seatId { get; set; }
        public bool isAvailable { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Seats Seats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
