//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Customers = new HashSet<Customers>();
        }
    
        public int ticketId { get; set; }
        public int roomId { get; set; }
        public int seatId { get; set; }
        public string seatName { get; set; }
        public int movieId { get; set; }
        public int screeningId { get; set; }
        public string TicketCode { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual RoomSeats RoomSeats { get; set; }
        public virtual Screening Screening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
